spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001    
spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.184.128:3306/cloudDB03              # 数据库名称
    username: dev
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.walter.springcloud.entities    # 所有Entity别名类所在包
  
eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com  # 自定义服务名称信息
    prefer-ip-address: true  # 访问路径可以显示IP地址
 
info:
  app.name: walter-microservicecloud-springcloudconfig02
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version} 
---
server:
  port: 8001    
spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.184.128:3306/cloudDB02              # 数据库名称
    username: dev
    password: 123456
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200    
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.walter.springcloud.entities    # 所有Entity别名类所在包
  
eureka:
  client:  # 客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: dept-8001.com  # 自定义服务名称信息
    prefer-ip-address: true  # 访问路径可以显示IP地址
 
info:
  app.name: walter-microservicecloud-springcloudconfig02
  company.name: www.baidu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version} 
